[supervisord]
nodaemon=true

[program:uvicorn]
command=/bin/bash -c "uvicorn srs_engine.main:app --host 0.0.0.0 --port $PORT"
environment=PYTHONUNBUFFERED=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autostart=true
autorestart=true
