from __future__ import annotations

import os
import re
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, Request
from fastapi.responses import FileResponse, RedirectResponse
from fastapi.templating import Jinja2Templates

from srs_engine.core.auth.deps import require_user

router = APIRouter()


# ── Helpers ──────────────────────────────────────────────────────────────────

def _templates(request: Request) -> Jinja2Templates:
    return request.app.state.templates  # type: ignore[attr-defined]


def _is_logged_in(request: Request) -> bool:
    return bool(request.session.get("user_id"))  # type: ignore[attr-defined]


def _render(request: Request, template: str, **ctx):
    """Shorthand to render a template with common context."""
    return _templates(request).TemplateResponse(
        template, {
            "request": request,
            "is_logged_in": _is_logged_in(request),
            "user": request.session.get("display_name"),
            **ctx
        }
    )


# ── Auth redirects ────────────────────────────────────────────────────────────

@router.get("/")
async def root(request: Request):
    """Always redirect root to /home. Login is only required for protected actions."""
    return RedirectResponse(url="/home", status_code=302)


@router.get("/login")
async def login_page(request: Request):
    """Show login page. Redirect to /home if already logged in."""
    if _is_logged_in(request):
        return RedirectResponse(url="/home", status_code=302)
    error = request.query_params.get("error")
    return _templates(request).TemplateResponse(
        "login.html", {"request": request, "error": error}
    )


# ── Public pages (no login required) ─────────────────────────────────────────

@router.get("/home")
async def home(request: Request):
    """Main landing page — single scrollable page (hero, features, faqs, about, contact)."""
    print("Rendering Home page")
    return _render(request, "pages/landing.html")


@router.get("/srs-generator")
async def srs_generator(request: Request):
    """SRS generator form — where users fill in project details to generate a .docx."""
    print("Rendering SRS Generator page")
    return _render(request, "pages/srs_generator.html")


# ── GET /api/my-documents ─────────────────────────────────────
@router.get("/api/my-documents")
async def get_my_documents(user=Depends(require_user)):
    """Return list of all SRS documents generated by the logged-in user."""
    user_id = str(user.get("_id"))
    user_dir = Path(f"./srs_engine/generated_srs/{user_id}")

    if not user_dir.exists():
        return []

    # BUG FIX: The original glob("*.docx") matched ALL docx files in the
    # directory, including versioned backup files created by the upgrader
    # (e.g. ProjectName_SRS_v1.docx, ProjectName_SRS_v2.docx).  Those
    # backups then appeared as phantom documents in the UI with garbled
    # names like "ProjectName v1".
    #
    # Fix: glob only the primary SRS files (*_SRS.docx) and additionally
    # skip any file whose name matches the versioned-backup pattern
    # (*_SRS_v<number>.docx) so that nothing slips through.
    _backup_pattern = re.compile(r"_SRS_v\d+\.docx$", re.IGNORECASE)

    raw_files = [
        f for f in user_dir.glob("*_SRS.docx")
        if not _backup_pattern.search(f.name)
    ]

    documents = []
    for file in sorted(raw_files, key=os.path.getmtime, reverse=True):
        stat = file.stat()
        # stem e.g. "MyProject_SRS" → project name "MyProject"
        project_name = file.stem.removesuffix("_SRS")

        documents.append({
            "id": file.stem,
            "project_name": project_name,
            "filename": file.name,
            "created_at": stat.st_mtime,
            "size_kb": round(stat.st_size / 1024, 1),
        })

    return documents


# ── GET /api/download-srs/{doc_id} ────────────────────────────
@router.get("/api/download-srs/{doc_id}")
async def download_srs(doc_id: str, user=Depends(require_user)):
    """Download a specific SRS .docx — scoped to the logged-in user."""
    user_id = str(user.get("_id"))

    if "/" in doc_id or "\\" in doc_id or ".." in doc_id:
        raise HTTPException(status_code=400, detail="Invalid document ID")

    file_path = Path(f"./srs_engine/generated_srs/{user_id}/{doc_id}.docx")

    if not file_path.exists():
        raise HTTPException(status_code=404, detail="Document not found")

    return FileResponse(
        path=str(file_path),
        filename=file_path.name,
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    )


# ── SRS Upgrader pages ────────────────────────────────────────

@router.get("/srs-upgrader")
async def srs_upgrader(request: Request):
    """Step 1: Upload page."""
    return _render(request, "pages/srs_upgrader.html")


# ── Generated SRS Upgrader pages ──────────────────────────────

@router.get("/srs-generated-upgrader")
async def srs_generated_upgrader(request: Request):
    """Pick a generated SRS document to upgrade."""
    return _render(request, "pages/srs_generated_upgrader.html")


@router.get("/srs-section-upgrader")
async def srs_section_upgrader(request: Request):
    """Upgrade individual sections of a generated SRS document."""
    return _render(request, "pages/srs_section_upgrader.html")


@router.get("/srs-history")
async def srs_history(request: Request):
    """View version history and restore old versions of a project."""
    return _render(request, "pages/srs_history.html")


@router.get("/srs-upgrader/review/{file_id}")
async def srs_upgrader_review(file_id: str, request: Request, user=Depends(require_user)):
    """Step 2: Analysis, Q&A, and diff review for a parsed SRS file."""
    from srs_engine.core.services.upload_service import list_uploads

    user_id = str(user.get("_id"))

    # Security: block path traversal
    if "/" in file_id or "\\" in file_id or ".." in file_id:
        raise HTTPException(status_code=400, detail="Invalid file ID")

    # Resolve original filename for display in the template
    uploads = await list_uploads(user_id)
    record = next((u for u in uploads if u["file_id"] == file_id), None)

    if not record:
        raise HTTPException(
            status_code=404,
            detail="File not found. Upload and parse it first.",
        )

    return _render(
        request,
        "pages/upgrader_review.html",
        file_id=file_id,
        filename=record["original_filename"],
    )

@router.get("/jobs")
async def jobs_page(request: Request):
    """
    Render the job tracker page.
    If user is not logged in, redirect to login page (HTML redirect, not JSON).
    Uses request.session directly to avoid returning a JSON 401.
    """
    user_id = request.session.get("user_id")
    if not user_id:
        # Hard redirect — never returns JSON to the browser
        return RedirectResponse(url="/login?next=/jobs", status_code=302)

    return request.app.state.templates.TemplateResponse(
        "pages/job_tracker.html",
        {
            "request":      request,
            "is_logged_in": True,
        },
    )

@router.get("/project-buckets")
async def project_buckets_page(request: Request):
    """
    Render the Project Buckets page.
    """
    user_id = request.session.get("user_id")
    if not user_id:
        return RedirectResponse(url="/login?next=/project-buckets", status_code=302)
    
    return _render(request, "pages/project_buckets.html")

@router.get("/document-navigator")
async def document_navigator_page(request: Request):
    """
    Render the new Agentic Document Navigator page.
    """
    user_id = request.session.get("user_id")
    if not user_id:
        return RedirectResponse(url="/login?next=/document-navigator", status_code=302)
    
    return _render(request, "pages/document_navigator.html")
 
