name: Deploy Worker to Hugging Face

on:
  push:
    branches: [ production_worker ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global credential.helper store
          echo "https://USER:${HF_TOKEN}@huggingface.co" > ~/.git-credentials

          git remote add hf https://huggingface.co/spaces/Smit1002/specforge-worker-2 || \
            git remote set-url hf https://huggingface.co/spaces/Smit1002/specforge-worker-2

          git push hf HEAD:main --force