name: Deploy Worker to Hugging Face

on:
  push:
    branches: [ production_worker ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://Smit1002:$HF_TOKEN@huggingface.co/spaces/Smit1002/specforge-worker-2 HEAD:main --force